### USERS

GET http://localhost:4000/pages

###

PATCH http://localhost:4000/users/6033891cb9538243b0b23061
Content-Type: application/json

{
  "name": "name",
  "password": "password",
  "email": "email2"
}

###

PATCH http://localhost:4000/pages/603e894eec470a30a0f788f8
Content-Type: application/json

{
  "title": "page3",
  "description": "description",
  "path": "/page3",
  "hidden": false,
  "onNavBar": true,
  "children": [
    {
      "title": "page4",
      "path": "/page4",
      "children": []
    },
    {
      "title": "page5",
      "path": "/page5",
      "children": []
    }
  ],
  "created_by": "6033891cb9538243b0b23061"
}

###

POST http://localhost:4000/modules
Content-Type: application/json

{
  "page": "6033beab1cbae847806d310e",
  "name": "module1",
  "type": "card",
  "position": {
    "x": 4,
    "y": 0,
    "w": 2,
    "h": 5
  },
  "body": {
    "title": "The first card",
    "text": "text",
    "img": "https://picsum.photos/200",
    "style": {
      "width": "18rem"
    }
  },
  "status": "active"
}

###

#POST http://localhost:4000/auth
#Content-Type: application/json
#
#{
#    "email": 'ja',
#    "password": 'ja'
#}